// source: mongorpc/value.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.mongorpc.ChangeStreamOptions');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.mongorpc.Timestamp');
goog.require('proto.mongorpc.Value');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ChangeStreamOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.ChangeStreamOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ChangeStreamOptions.displayName = 'proto.mongorpc.ChangeStreamOptions';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.ChangeStreamOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.ChangeStreamOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.ChangeStreamOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ChangeStreamOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    batchSize: jspb.Message.getFieldWithDefault(msg, 1, 0),
    fullDocument: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    startAtOperationTime: (f = msg.getStartAtOperationTime()) && proto.mongorpc.Timestamp.toObject(includeInstance, f),
    maxAwaitTimeMs: (f = msg.getMaxAwaitTimeMs()) && proto.mongorpc.Timestamp.toObject(includeInstance, f),
    resumeAfter: (f = msg.getResumeAfter()) && proto.mongorpc.Value.toObject(includeInstance, f),
    collation: (f = msg.getCollation()) && proto.mongorpc.Value.toObject(includeInstance, f),
    startAfter: (f = msg.getStartAfter()) && proto.mongorpc.Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ChangeStreamOptions}
 */
proto.mongorpc.ChangeStreamOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ChangeStreamOptions;
  return proto.mongorpc.ChangeStreamOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ChangeStreamOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ChangeStreamOptions}
 */
proto.mongorpc.ChangeStreamOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBatchSize(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFullDocument(value);
      break;
    case 4:
      var value = new proto.mongorpc.Timestamp;
      reader.readMessage(value,proto.mongorpc.Timestamp.deserializeBinaryFromReader);
      msg.setStartAtOperationTime(value);
      break;
    case 5:
      var value = new proto.mongorpc.Timestamp;
      reader.readMessage(value,proto.mongorpc.Timestamp.deserializeBinaryFromReader);
      msg.setMaxAwaitTimeMs(value);
      break;
    case 6:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setResumeAfter(value);
      break;
    case 7:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setCollation(value);
      break;
    case 8:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setStartAfter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ChangeStreamOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ChangeStreamOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ChangeStreamOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ChangeStreamOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBatchSize();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getFullDocument();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getStartAtOperationTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.mongorpc.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMaxAwaitTimeMs();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.mongorpc.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResumeAfter();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getCollation();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getStartAfter();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 batch_size = 1;
 * @return {number}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getBatchSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.setBatchSize = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool full_document = 3;
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getFullDocument = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.setFullDocument = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional Timestamp start_at_operation_time = 4;
 * @return {?proto.mongorpc.Timestamp}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getStartAtOperationTime = function() {
  return /** @type{?proto.mongorpc.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Timestamp, 4));
};


/**
 * @param {?proto.mongorpc.Timestamp|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setStartAtOperationTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearStartAtOperationTime = function() {
  return this.setStartAtOperationTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasStartAtOperationTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Timestamp max_await_time_ms = 5;
 * @return {?proto.mongorpc.Timestamp}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getMaxAwaitTimeMs = function() {
  return /** @type{?proto.mongorpc.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Timestamp, 5));
};


/**
 * @param {?proto.mongorpc.Timestamp|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setMaxAwaitTimeMs = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearMaxAwaitTimeMs = function() {
  return this.setMaxAwaitTimeMs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasMaxAwaitTimeMs = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Value resume_after = 6;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getResumeAfter = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 6));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setResumeAfter = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearResumeAfter = function() {
  return this.setResumeAfter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasResumeAfter = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Value collation = 7;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getCollation = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 7));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setCollation = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearCollation = function() {
  return this.setCollation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasCollation = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Value start_after = 8;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getStartAfter = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 8));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setStartAfter = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearStartAfter = function() {
  return this.setStartAfter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasStartAfter = function() {
  return jspb.Message.getField(this, 8) != null;
};


