// source: mongorpc/mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.mongorpc.ListenRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.mongorpc.ChangeStreamOptions');
goog.require('proto.mongorpc.Value');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ListenRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mongorpc.ListenRequest.repeatedFields_, null);
};
goog.inherits(proto.mongorpc.ListenRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ListenRequest.displayName = 'proto.mongorpc.ListenRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mongorpc.ListenRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.ListenRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.ListenRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.ListenRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ListenRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    database: jspb.Message.getFieldWithDefault(msg, 1, ""),
    collection: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pipelineList: jspb.Message.toObjectList(msg.getPipelineList(),
    proto.mongorpc.Value.toObject, includeInstance),
    options: (f = msg.getOptions()) && proto.mongorpc.ChangeStreamOptions.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ListenRequest}
 */
proto.mongorpc.ListenRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ListenRequest;
  return proto.mongorpc.ListenRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ListenRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ListenRequest}
 */
proto.mongorpc.ListenRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatabase(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCollection(value);
      break;
    case 3:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.addPipeline(value);
      break;
    case 4:
      var value = new proto.mongorpc.ChangeStreamOptions;
      reader.readMessage(value,proto.mongorpc.ChangeStreamOptions.deserializeBinaryFromReader);
      msg.setOptions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ListenRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ListenRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ListenRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ListenRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatabase();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCollection();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPipelineList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getOptions();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.mongorpc.ChangeStreamOptions.serializeBinaryToWriter
    );
  }
};


/**
 * optional string database = 1;
 * @return {string}
 */
proto.mongorpc.ListenRequest.prototype.getDatabase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.ListenRequest} returns this
 */
proto.mongorpc.ListenRequest.prototype.setDatabase = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string collection = 2;
 * @return {string}
 */
proto.mongorpc.ListenRequest.prototype.getCollection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.ListenRequest} returns this
 */
proto.mongorpc.ListenRequest.prototype.setCollection = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Value pipeline = 3;
 * @return {!Array<!proto.mongorpc.Value>}
 */
proto.mongorpc.ListenRequest.prototype.getPipelineList = function() {
  return /** @type{!Array<!proto.mongorpc.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mongorpc.Value, 3));
};


/**
 * @param {!Array<!proto.mongorpc.Value>} value
 * @return {!proto.mongorpc.ListenRequest} returns this
*/
proto.mongorpc.ListenRequest.prototype.setPipelineList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.mongorpc.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.ListenRequest.prototype.addPipeline = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.mongorpc.Value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mongorpc.ListenRequest} returns this
 */
proto.mongorpc.ListenRequest.prototype.clearPipelineList = function() {
  return this.setPipelineList([]);
};


/**
 * optional ChangeStreamOptions options = 4;
 * @return {?proto.mongorpc.ChangeStreamOptions}
 */
proto.mongorpc.ListenRequest.prototype.getOptions = function() {
  return /** @type{?proto.mongorpc.ChangeStreamOptions} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.ChangeStreamOptions, 4));
};


/**
 * @param {?proto.mongorpc.ChangeStreamOptions|undefined} value
 * @return {!proto.mongorpc.ListenRequest} returns this
*/
proto.mongorpc.ListenRequest.prototype.setOptions = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ListenRequest} returns this
 */
proto.mongorpc.ListenRequest.prototype.clearOptions = function() {
  return this.setOptions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ListenRequest.prototype.hasOptions = function() {
  return jspb.Message.getField(this, 4) != null;
};


