// source: mongorpc/mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.mongorpc.QueryDocumentsRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.mongorpc.Value');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.QueryDocumentsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.QueryDocumentsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.QueryDocumentsRequest.displayName = 'proto.mongorpc.QueryDocumentsRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.QueryDocumentsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.QueryDocumentsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.QueryDocumentsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    database: jspb.Message.getFieldWithDefault(msg, 1, ""),
    collection: jspb.Message.getFieldWithDefault(msg, 2, ""),
    query: (f = msg.getQuery()) && proto.mongorpc.Value.toObject(includeInstance, f),
    sort: (f = msg.getSort()) && proto.mongorpc.Value.toObject(includeInstance, f),
    projection: (f = msg.getProjection()) && proto.mongorpc.Value.toObject(includeInstance, f),
    skip: jspb.Message.getFieldWithDefault(msg, 6, 0),
    limit: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.QueryDocumentsRequest}
 */
proto.mongorpc.QueryDocumentsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.QueryDocumentsRequest;
  return proto.mongorpc.QueryDocumentsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.QueryDocumentsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.QueryDocumentsRequest}
 */
proto.mongorpc.QueryDocumentsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatabase(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCollection(value);
      break;
    case 3:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setQuery(value);
      break;
    case 4:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setSort(value);
      break;
    case 5:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setProjection(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkip(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLimit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.QueryDocumentsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.QueryDocumentsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.QueryDocumentsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatabase();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCollection();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getQuery();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getSort();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getProjection();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getSkip();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional string database = 1;
 * @return {string}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.getDatabase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
 */
proto.mongorpc.QueryDocumentsRequest.prototype.setDatabase = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string collection = 2;
 * @return {string}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.getCollection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
 */
proto.mongorpc.QueryDocumentsRequest.prototype.setCollection = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Value query = 3;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.getQuery = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 3));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
*/
proto.mongorpc.QueryDocumentsRequest.prototype.setQuery = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
 */
proto.mongorpc.QueryDocumentsRequest.prototype.clearQuery = function() {
  return this.setQuery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.hasQuery = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Value sort = 4;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.getSort = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 4));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
*/
proto.mongorpc.QueryDocumentsRequest.prototype.setSort = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
 */
proto.mongorpc.QueryDocumentsRequest.prototype.clearSort = function() {
  return this.setSort(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.hasSort = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Value projection = 5;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.getProjection = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 5));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
*/
proto.mongorpc.QueryDocumentsRequest.prototype.setProjection = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
 */
proto.mongorpc.QueryDocumentsRequest.prototype.clearProjection = function() {
  return this.setProjection(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.hasProjection = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 skip = 6;
 * @return {number}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.getSkip = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
 */
proto.mongorpc.QueryDocumentsRequest.prototype.setSkip = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 limit = 7;
 * @return {number}
 */
proto.mongorpc.QueryDocumentsRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.QueryDocumentsRequest} returns this
 */
proto.mongorpc.QueryDocumentsRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


