// source: mongorpc/mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.mongorpc.UpdateDocumentRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.mongorpc.ObjectId');
goog.require('proto.mongorpc.Value');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.UpdateDocumentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.UpdateDocumentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.UpdateDocumentRequest.displayName = 'proto.mongorpc.UpdateDocumentRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.UpdateDocumentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.UpdateDocumentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.UpdateDocumentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    database: jspb.Message.getFieldWithDefault(msg, 1, ""),
    collection: jspb.Message.getFieldWithDefault(msg, 2, ""),
    documentId: (f = msg.getDocumentId()) && proto.mongorpc.ObjectId.toObject(includeInstance, f),
    document: (f = msg.getDocument()) && proto.mongorpc.Value.toObject(includeInstance, f),
    replace: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.UpdateDocumentRequest}
 */
proto.mongorpc.UpdateDocumentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.UpdateDocumentRequest;
  return proto.mongorpc.UpdateDocumentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.UpdateDocumentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.UpdateDocumentRequest}
 */
proto.mongorpc.UpdateDocumentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatabase(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCollection(value);
      break;
    case 3:
      var value = new proto.mongorpc.ObjectId;
      reader.readMessage(value,proto.mongorpc.ObjectId.deserializeBinaryFromReader);
      msg.setDocumentId(value);
      break;
    case 4:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setDocument(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReplace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.UpdateDocumentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.UpdateDocumentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.UpdateDocumentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatabase();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCollection();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDocumentId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.mongorpc.ObjectId.serializeBinaryToWriter
    );
  }
  f = message.getDocument();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getReplace();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional string database = 1;
 * @return {string}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.getDatabase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.UpdateDocumentRequest} returns this
 */
proto.mongorpc.UpdateDocumentRequest.prototype.setDatabase = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string collection = 2;
 * @return {string}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.getCollection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.UpdateDocumentRequest} returns this
 */
proto.mongorpc.UpdateDocumentRequest.prototype.setCollection = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ObjectId document_id = 3;
 * @return {?proto.mongorpc.ObjectId}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.getDocumentId = function() {
  return /** @type{?proto.mongorpc.ObjectId} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.ObjectId, 3));
};


/**
 * @param {?proto.mongorpc.ObjectId|undefined} value
 * @return {!proto.mongorpc.UpdateDocumentRequest} returns this
*/
proto.mongorpc.UpdateDocumentRequest.prototype.setDocumentId = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.UpdateDocumentRequest} returns this
 */
proto.mongorpc.UpdateDocumentRequest.prototype.clearDocumentId = function() {
  return this.setDocumentId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.hasDocumentId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Value document = 4;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.getDocument = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 4));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.UpdateDocumentRequest} returns this
*/
proto.mongorpc.UpdateDocumentRequest.prototype.setDocument = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.UpdateDocumentRequest} returns this
 */
proto.mongorpc.UpdateDocumentRequest.prototype.clearDocument = function() {
  return this.setDocument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.hasDocument = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool replace = 5;
 * @return {boolean}
 */
proto.mongorpc.UpdateDocumentRequest.prototype.getReplace = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.mongorpc.UpdateDocumentRequest} returns this
 */
proto.mongorpc.UpdateDocumentRequest.prototype.setReplace = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


