// source: mongorpc/value.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.mongorpc.ArrayValue', null, global);
goog.exportSymbol('proto.mongorpc.ChangeStreamOptions', null, global);
goog.exportSymbol('proto.mongorpc.Empty', null, global);
goog.exportSymbol('proto.mongorpc.MapValue', null, global);
goog.exportSymbol('proto.mongorpc.NullValue', null, global);
goog.exportSymbol('proto.mongorpc.ObjectId', null, global);
goog.exportSymbol('proto.mongorpc.Timestamp', null, global);
goog.exportSymbol('proto.mongorpc.Value', null, global);
goog.exportSymbol('proto.mongorpc.Value.TypeCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.Empty.displayName = 'proto.mongorpc.Empty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ArrayValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mongorpc.ArrayValue.repeatedFields_, null);
};
goog.inherits(proto.mongorpc.ArrayValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ArrayValue.displayName = 'proto.mongorpc.ArrayValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.MapValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.MapValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.MapValue.displayName = 'proto.mongorpc.MapValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.Timestamp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.Timestamp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.Timestamp.displayName = 'proto.mongorpc.Timestamp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ObjectId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.ObjectId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ObjectId.displayName = 'proto.mongorpc.ObjectId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.Value = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.mongorpc.Value.oneofGroups_);
};
goog.inherits(proto.mongorpc.Value, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.Value.displayName = 'proto.mongorpc.Value';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ChangeStreamOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.ChangeStreamOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ChangeStreamOptions.displayName = 'proto.mongorpc.ChangeStreamOptions';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.Empty}
 */
proto.mongorpc.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.Empty;
  return proto.mongorpc.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.Empty}
 */
proto.mongorpc.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mongorpc.ArrayValue.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.ArrayValue.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.ArrayValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.ArrayValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ArrayValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    valuesList: jspb.Message.toObjectList(msg.getValuesList(),
    proto.mongorpc.Value.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ArrayValue}
 */
proto.mongorpc.ArrayValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ArrayValue;
  return proto.mongorpc.ArrayValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ArrayValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ArrayValue}
 */
proto.mongorpc.ArrayValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.addValues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ArrayValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ArrayValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ArrayValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ArrayValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Value values = 1;
 * @return {!Array<!proto.mongorpc.Value>}
 */
proto.mongorpc.ArrayValue.prototype.getValuesList = function() {
  return /** @type{!Array<!proto.mongorpc.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mongorpc.Value, 1));
};


/**
 * @param {!Array<!proto.mongorpc.Value>} value
 * @return {!proto.mongorpc.ArrayValue} returns this
*/
proto.mongorpc.ArrayValue.prototype.setValuesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.mongorpc.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.ArrayValue.prototype.addValues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.mongorpc.Value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mongorpc.ArrayValue} returns this
 */
proto.mongorpc.ArrayValue.prototype.clearValuesList = function() {
  return this.setValuesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.MapValue.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.MapValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.MapValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.MapValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldsMap: (f = msg.getFieldsMap()) ? f.toObject(includeInstance, proto.mongorpc.Value.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.MapValue}
 */
proto.mongorpc.MapValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.MapValue;
  return proto.mongorpc.MapValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.MapValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.MapValue}
 */
proto.mongorpc.MapValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getFieldsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.mongorpc.Value.deserializeBinaryFromReader, "", new proto.mongorpc.Value());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.MapValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.MapValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.MapValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.MapValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFieldsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.mongorpc.Value.serializeBinaryToWriter);
  }
};


/**
 * map<string, Value> fields = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.mongorpc.Value>}
 */
proto.mongorpc.MapValue.prototype.getFieldsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.mongorpc.Value>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.mongorpc.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.mongorpc.MapValue} returns this
 */
proto.mongorpc.MapValue.prototype.clearFieldsMap = function() {
  this.getFieldsMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.Timestamp.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.Timestamp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.Timestamp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Timestamp.toObject = function(includeInstance, msg) {
  var f, obj = {
    seconds: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nanos: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.Timestamp}
 */
proto.mongorpc.Timestamp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.Timestamp;
  return proto.mongorpc.Timestamp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.Timestamp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.Timestamp}
 */
proto.mongorpc.Timestamp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSeconds(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNanos(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.Timestamp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.Timestamp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.Timestamp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Timestamp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSeconds();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getNanos();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int64 seconds = 1;
 * @return {number}
 */
proto.mongorpc.Timestamp.prototype.getSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.Timestamp} returns this
 */
proto.mongorpc.Timestamp.prototype.setSeconds = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 nanos = 2;
 * @return {number}
 */
proto.mongorpc.Timestamp.prototype.getNanos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.Timestamp} returns this
 */
proto.mongorpc.Timestamp.prototype.setNanos = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.ObjectId.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.ObjectId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.ObjectId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ObjectId.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ObjectId}
 */
proto.mongorpc.ObjectId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ObjectId;
  return proto.mongorpc.ObjectId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ObjectId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ObjectId}
 */
proto.mongorpc.ObjectId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ObjectId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ObjectId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ObjectId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ObjectId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.mongorpc.ObjectId.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.ObjectId} returns this
 */
proto.mongorpc.ObjectId.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.mongorpc.Value.oneofGroups_ = [[1,2,3,4,5,6,7,8,9,10]];

/**
 * @enum {number}
 */
proto.mongorpc.Value.TypeCase = {
  TYPE_NOT_SET: 0,
  INTEGER32_VALUE: 1,
  INTEGER64_VALUE: 2,
  BOOLEAN_VALUE: 3,
  STRING_VALUE: 4,
  DOUBLE_VALUE: 5,
  NULL_VALUE: 6,
  ARRAY_VALUE: 7,
  MAP_VALUE: 8,
  OBJECT_ID_VALUE: 9,
  TIMESTAMP_VALUE: 10
};

/**
 * @return {proto.mongorpc.Value.TypeCase}
 */
proto.mongorpc.Value.prototype.getTypeCase = function() {
  return /** @type {proto.mongorpc.Value.TypeCase} */(jspb.Message.computeOneofCase(this, proto.mongorpc.Value.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.Value.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.Value.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.Value} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Value.toObject = function(includeInstance, msg) {
  var f, obj = {
    integer32Value: jspb.Message.getFieldWithDefault(msg, 1, 0),
    integer64Value: jspb.Message.getFieldWithDefault(msg, 2, 0),
    booleanValue: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    stringValue: jspb.Message.getFieldWithDefault(msg, 4, ""),
    doubleValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    nullValue: jspb.Message.getFieldWithDefault(msg, 6, 0),
    arrayValue: (f = msg.getArrayValue()) && proto.mongorpc.ArrayValue.toObject(includeInstance, f),
    mapValue: (f = msg.getMapValue()) && proto.mongorpc.MapValue.toObject(includeInstance, f),
    objectIdValue: (f = msg.getObjectIdValue()) && proto.mongorpc.ObjectId.toObject(includeInstance, f),
    timestampValue: (f = msg.getTimestampValue()) && proto.mongorpc.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.Value.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.Value;
  return proto.mongorpc.Value.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.Value} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.Value.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInteger32Value(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInteger64Value(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBooleanValue(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringValue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDoubleValue(value);
      break;
    case 6:
      var value = /** @type {!proto.mongorpc.NullValue} */ (reader.readEnum());
      msg.setNullValue(value);
      break;
    case 7:
      var value = new proto.mongorpc.ArrayValue;
      reader.readMessage(value,proto.mongorpc.ArrayValue.deserializeBinaryFromReader);
      msg.setArrayValue(value);
      break;
    case 8:
      var value = new proto.mongorpc.MapValue;
      reader.readMessage(value,proto.mongorpc.MapValue.deserializeBinaryFromReader);
      msg.setMapValue(value);
      break;
    case 9:
      var value = new proto.mongorpc.ObjectId;
      reader.readMessage(value,proto.mongorpc.ObjectId.deserializeBinaryFromReader);
      msg.setObjectIdValue(value);
      break;
    case 10:
      var value = new proto.mongorpc.Timestamp;
      reader.readMessage(value,proto.mongorpc.Timestamp.deserializeBinaryFromReader);
      msg.setTimestampValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.Value.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.Value.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.Value} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Value.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {!proto.mongorpc.NullValue} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getArrayValue();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.mongorpc.ArrayValue.serializeBinaryToWriter
    );
  }
  f = message.getMapValue();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.mongorpc.MapValue.serializeBinaryToWriter
    );
  }
  f = message.getObjectIdValue();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.mongorpc.ObjectId.serializeBinaryToWriter
    );
  }
  f = message.getTimestampValue();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.mongorpc.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 integer32_value = 1;
 * @return {number}
 */
proto.mongorpc.Value.prototype.getInteger32Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setInteger32Value = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearInteger32Value = function() {
  return jspb.Message.setOneofField(this, 1, proto.mongorpc.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasInteger32Value = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 integer64_value = 2;
 * @return {number}
 */
proto.mongorpc.Value.prototype.getInteger64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setInteger64Value = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearInteger64Value = function() {
  return jspb.Message.setOneofField(this, 2, proto.mongorpc.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasInteger64Value = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool boolean_value = 3;
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.getBooleanValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setBooleanValue = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearBooleanValue = function() {
  return jspb.Message.setOneofField(this, 3, proto.mongorpc.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasBooleanValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string string_value = 4;
 * @return {string}
 */
proto.mongorpc.Value.prototype.getStringValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setStringValue = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearStringValue = function() {
  return jspb.Message.setOneofField(this, 4, proto.mongorpc.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasStringValue = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double double_value = 5;
 * @return {number}
 */
proto.mongorpc.Value.prototype.getDoubleValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setDoubleValue = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearDoubleValue = function() {
  return jspb.Message.setOneofField(this, 5, proto.mongorpc.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasDoubleValue = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional NullValue null_value = 6;
 * @return {!proto.mongorpc.NullValue}
 */
proto.mongorpc.Value.prototype.getNullValue = function() {
  return /** @type {!proto.mongorpc.NullValue} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.mongorpc.NullValue} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setNullValue = function(value) {
  return jspb.Message.setOneofField(this, 6, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearNullValue = function() {
  return jspb.Message.setOneofField(this, 6, proto.mongorpc.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasNullValue = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ArrayValue array_value = 7;
 * @return {?proto.mongorpc.ArrayValue}
 */
proto.mongorpc.Value.prototype.getArrayValue = function() {
  return /** @type{?proto.mongorpc.ArrayValue} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.ArrayValue, 7));
};


/**
 * @param {?proto.mongorpc.ArrayValue|undefined} value
 * @return {!proto.mongorpc.Value} returns this
*/
proto.mongorpc.Value.prototype.setArrayValue = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearArrayValue = function() {
  return this.setArrayValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasArrayValue = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional MapValue map_value = 8;
 * @return {?proto.mongorpc.MapValue}
 */
proto.mongorpc.Value.prototype.getMapValue = function() {
  return /** @type{?proto.mongorpc.MapValue} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.MapValue, 8));
};


/**
 * @param {?proto.mongorpc.MapValue|undefined} value
 * @return {!proto.mongorpc.Value} returns this
*/
proto.mongorpc.Value.prototype.setMapValue = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearMapValue = function() {
  return this.setMapValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasMapValue = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional ObjectId object_id_value = 9;
 * @return {?proto.mongorpc.ObjectId}
 */
proto.mongorpc.Value.prototype.getObjectIdValue = function() {
  return /** @type{?proto.mongorpc.ObjectId} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.ObjectId, 9));
};


/**
 * @param {?proto.mongorpc.ObjectId|undefined} value
 * @return {!proto.mongorpc.Value} returns this
*/
proto.mongorpc.Value.prototype.setObjectIdValue = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearObjectIdValue = function() {
  return this.setObjectIdValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasObjectIdValue = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Timestamp timestamp_value = 10;
 * @return {?proto.mongorpc.Timestamp}
 */
proto.mongorpc.Value.prototype.getTimestampValue = function() {
  return /** @type{?proto.mongorpc.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Timestamp, 10));
};


/**
 * @param {?proto.mongorpc.Timestamp|undefined} value
 * @return {!proto.mongorpc.Value} returns this
*/
proto.mongorpc.Value.prototype.setTimestampValue = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.mongorpc.Value.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearTimestampValue = function() {
  return this.setTimestampValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasTimestampValue = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.ChangeStreamOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.ChangeStreamOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.ChangeStreamOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ChangeStreamOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    batchSize: jspb.Message.getFieldWithDefault(msg, 1, 0),
    fullDocument: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    startAtOperationTime: (f = msg.getStartAtOperationTime()) && proto.mongorpc.Timestamp.toObject(includeInstance, f),
    maxAwaitTimeMs: (f = msg.getMaxAwaitTimeMs()) && proto.mongorpc.Timestamp.toObject(includeInstance, f),
    resumeAfter: (f = msg.getResumeAfter()) && proto.mongorpc.Value.toObject(includeInstance, f),
    collation: (f = msg.getCollation()) && proto.mongorpc.Value.toObject(includeInstance, f),
    startAfter: (f = msg.getStartAfter()) && proto.mongorpc.Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ChangeStreamOptions}
 */
proto.mongorpc.ChangeStreamOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ChangeStreamOptions;
  return proto.mongorpc.ChangeStreamOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ChangeStreamOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ChangeStreamOptions}
 */
proto.mongorpc.ChangeStreamOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBatchSize(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFullDocument(value);
      break;
    case 4:
      var value = new proto.mongorpc.Timestamp;
      reader.readMessage(value,proto.mongorpc.Timestamp.deserializeBinaryFromReader);
      msg.setStartAtOperationTime(value);
      break;
    case 5:
      var value = new proto.mongorpc.Timestamp;
      reader.readMessage(value,proto.mongorpc.Timestamp.deserializeBinaryFromReader);
      msg.setMaxAwaitTimeMs(value);
      break;
    case 6:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setResumeAfter(value);
      break;
    case 7:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setCollation(value);
      break;
    case 8:
      var value = new proto.mongorpc.Value;
      reader.readMessage(value,proto.mongorpc.Value.deserializeBinaryFromReader);
      msg.setStartAfter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ChangeStreamOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ChangeStreamOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ChangeStreamOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ChangeStreamOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBatchSize();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getFullDocument();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getStartAtOperationTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.mongorpc.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMaxAwaitTimeMs();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.mongorpc.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResumeAfter();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getCollation();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
  f = message.getStartAfter();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 batch_size = 1;
 * @return {number}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getBatchSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.setBatchSize = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool full_document = 3;
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getFullDocument = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.setFullDocument = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional Timestamp start_at_operation_time = 4;
 * @return {?proto.mongorpc.Timestamp}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getStartAtOperationTime = function() {
  return /** @type{?proto.mongorpc.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Timestamp, 4));
};


/**
 * @param {?proto.mongorpc.Timestamp|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setStartAtOperationTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearStartAtOperationTime = function() {
  return this.setStartAtOperationTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasStartAtOperationTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Timestamp max_await_time_ms = 5;
 * @return {?proto.mongorpc.Timestamp}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getMaxAwaitTimeMs = function() {
  return /** @type{?proto.mongorpc.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Timestamp, 5));
};


/**
 * @param {?proto.mongorpc.Timestamp|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setMaxAwaitTimeMs = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearMaxAwaitTimeMs = function() {
  return this.setMaxAwaitTimeMs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasMaxAwaitTimeMs = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Value resume_after = 6;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getResumeAfter = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 6));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setResumeAfter = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearResumeAfter = function() {
  return this.setResumeAfter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasResumeAfter = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Value collation = 7;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getCollation = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 7));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setCollation = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearCollation = function() {
  return this.setCollation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasCollation = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Value start_after = 8;
 * @return {?proto.mongorpc.Value}
 */
proto.mongorpc.ChangeStreamOptions.prototype.getStartAfter = function() {
  return /** @type{?proto.mongorpc.Value} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Value, 8));
};


/**
 * @param {?proto.mongorpc.Value|undefined} value
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
*/
proto.mongorpc.ChangeStreamOptions.prototype.setStartAfter = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ChangeStreamOptions} returns this
 */
proto.mongorpc.ChangeStreamOptions.prototype.clearStartAfter = function() {
  return this.setStartAfter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ChangeStreamOptions.prototype.hasStartAfter = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * @enum {number}
 */
proto.mongorpc.NullValue = {
  NULL_VALUE: 0
};

goog.object.extend(exports, proto.mongorpc);
