// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide("proto.mongorpc.ArrayValue");
goog.provide("proto.mongorpc.MapValue");
goog.provide("proto.mongorpc.Value");
goog.provide("proto.mongorpc.Value.TypeCase");

goog.require("jspb.BinaryReader");
goog.require("jspb.BinaryWriter");
goog.require("jspb.Map");
goog.require("jspb.Message");
goog.require("proto.mongorpc.ObjectID");
goog.require("proto.mongorpc.Timestamp");

goog.forwardDeclare("proto.mongorpc.NullValue");
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ArrayValue = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.mongorpc.ArrayValue.repeatedFields_,
    null
  );
};
goog.inherits(proto.mongorpc.ArrayValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ArrayValue.displayName = "proto.mongorpc.ArrayValue";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.MapValue = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.MapValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.MapValue.displayName = "proto.mongorpc.MapValue";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.Value = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    null,
    proto.mongorpc.Value.oneofGroups_
  );
};
goog.inherits(proto.mongorpc.Value, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.Value.displayName = "proto.mongorpc.Value";
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mongorpc.ArrayValue.repeatedFields_ = [1];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.ArrayValue.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.mongorpc.ArrayValue.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.ArrayValue} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.ArrayValue.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        valuesList: jspb.Message.toObjectList(
          msg.getValuesList(),
          proto.mongorpc.Value.toObject,
          includeInstance
        ),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ArrayValue}
 */
proto.mongorpc.ArrayValue.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ArrayValue();
  return proto.mongorpc.ArrayValue.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ArrayValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ArrayValue}
 */
proto.mongorpc.ArrayValue.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.mongorpc.Value();
        reader.readMessage(
          value,
          proto.mongorpc.Value.deserializeBinaryFromReader
        );
        msg.addValues(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ArrayValue.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ArrayValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ArrayValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ArrayValue.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
};

/**
 * repeated Value values = 1;
 * @return {!Array<!proto.mongorpc.Value>}
 */
proto.mongorpc.ArrayValue.prototype.getValuesList = function () {
  return /** @type{!Array<!proto.mongorpc.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mongorpc.Value, 1)
  );
};

/**
 * @param {!Array<!proto.mongorpc.Value>} value
 * @return {!proto.mongorpc.ArrayValue} returns this
 */
proto.mongorpc.ArrayValue.prototype.setValuesList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};

/**
 * @param {!proto.mongorpc.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.ArrayValue.prototype.addValues = function (
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.mongorpc.Value,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mongorpc.ArrayValue} returns this
 */
proto.mongorpc.ArrayValue.prototype.clearValuesList = function () {
  return this.setValuesList([]);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.MapValue.prototype.toObject = function (opt_includeInstance) {
    return proto.mongorpc.MapValue.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.MapValue} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.MapValue.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        fieldsMap: (f = msg.getFieldsMap())
          ? f.toObject(includeInstance, proto.mongorpc.Value.toObject)
          : [],
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.MapValue}
 */
proto.mongorpc.MapValue.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.MapValue();
  return proto.mongorpc.MapValue.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.MapValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.MapValue}
 */
proto.mongorpc.MapValue.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = msg.getFieldsMap();
        reader.readMessage(value, function (message, reader) {
          jspb.Map.deserializeBinary(
            message,
            reader,
            jspb.BinaryReader.prototype.readString,
            jspb.BinaryReader.prototype.readMessage,
            proto.mongorpc.Value.deserializeBinaryFromReader,
            "",
            new proto.mongorpc.Value()
          );
        });
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.MapValue.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.MapValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.MapValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.MapValue.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getFieldsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(
      1,
      writer,
      jspb.BinaryWriter.prototype.writeString,
      jspb.BinaryWriter.prototype.writeMessage,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
};

/**
 * map<string, Value> fields = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.mongorpc.Value>}
 */
proto.mongorpc.MapValue.prototype.getFieldsMap = function (opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.mongorpc.Value>} */ (
    jspb.Message.getMapField(this, 1, opt_noLazyCreate, proto.mongorpc.Value)
  );
};

/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.mongorpc.MapValue} returns this
 */
proto.mongorpc.MapValue.prototype.clearFieldsMap = function () {
  this.getFieldsMap().clear();
  return this;
};

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.mongorpc.Value.oneofGroups_ = [[1, 2, 3, 4, 5, 8, 9, 10, 23, 7]];

/**
 * @enum {number}
 */
proto.mongorpc.Value.TypeCase = {
  TYPE_NOT_SET: 0,
  DOUBLE_VALUE: 1,
  STRING_VALUE: 2,
  MAP_VALUE: 3,
  ARRAY_VALUE: 4,
  BYTES_VALUE: 5,
  BOOL_VALUE: 8,
  DATE_VALUE: 9,
  NULL_VALUE: 10,
  INTEGER_VALUE: 23,
  OBJECT_ID_VALUE: 7,
};

/**
 * @return {proto.mongorpc.Value.TypeCase}
 */
proto.mongorpc.Value.prototype.getTypeCase = function () {
  return /** @type {proto.mongorpc.Value.TypeCase} */ (
    jspb.Message.computeOneofCase(this, proto.mongorpc.Value.oneofGroups_[0])
  );
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.Value.prototype.toObject = function (opt_includeInstance) {
    return proto.mongorpc.Value.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.Value} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.Value.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        doubleValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
        stringValue: jspb.Message.getFieldWithDefault(msg, 2, ""),
        mapValue:
          (f = msg.getMapValue()) &&
          proto.mongorpc.MapValue.toObject(includeInstance, f),
        arrayValue:
          (f = msg.getArrayValue()) &&
          proto.mongorpc.ArrayValue.toObject(includeInstance, f),
        bytesValue: msg.getBytesValue_asB64(),
        boolValue: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
        dateValue:
          (f = msg.getDateValue()) &&
          proto.mongorpc.Timestamp.toObject(includeInstance, f),
        nullValue: jspb.Message.getFieldWithDefault(msg, 10, 0),
        integerValue: jspb.Message.getFieldWithDefault(msg, 23, 0),
        objectIdValue:
          (f = msg.getObjectIdValue()) &&
          proto.mongorpc.ObjectID.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.Value.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.Value();
  return proto.mongorpc.Value.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.Value} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.Value.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readDouble());
        msg.setDoubleValue(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setStringValue(value);
        break;
      case 3:
        var value = new proto.mongorpc.MapValue();
        reader.readMessage(
          value,
          proto.mongorpc.MapValue.deserializeBinaryFromReader
        );
        msg.setMapValue(value);
        break;
      case 4:
        var value = new proto.mongorpc.ArrayValue();
        reader.readMessage(
          value,
          proto.mongorpc.ArrayValue.deserializeBinaryFromReader
        );
        msg.setArrayValue(value);
        break;
      case 5:
        var value = /** @type {!Uint8Array} */ (reader.readBytes());
        msg.setBytesValue(value);
        break;
      case 8:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setBoolValue(value);
        break;
      case 9:
        var value = new proto.mongorpc.Timestamp();
        reader.readMessage(
          value,
          proto.mongorpc.Timestamp.deserializeBinaryFromReader
        );
        msg.setDateValue(value);
        break;
      case 10:
        var value = /** @type {!proto.mongorpc.NullValue} */ (
          reader.readEnum()
        );
        msg.setNullValue(value);
        break;
      case 23:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setIntegerValue(value);
        break;
      case 7:
        var value = new proto.mongorpc.ObjectID();
        reader.readMessage(
          value,
          proto.mongorpc.ObjectID.deserializeBinaryFromReader
        );
        msg.setObjectIdValue(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.Value.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.Value.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.Value} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Value.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(1, f);
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(2, f);
  }
  f = message.getMapValue();
  if (f != null) {
    writer.writeMessage(3, f, proto.mongorpc.MapValue.serializeBinaryToWriter);
  }
  f = message.getArrayValue();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.mongorpc.ArrayValue.serializeBinaryToWriter
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBytes(5, f);
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBool(8, f);
  }
  f = message.getDateValue();
  if (f != null) {
    writer.writeMessage(9, f, proto.mongorpc.Timestamp.serializeBinaryToWriter);
  }
  f = /** @type {!proto.mongorpc.NullValue} */ (
    jspb.Message.getField(message, 10)
  );
  if (f != null) {
    writer.writeEnum(10, f);
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 23));
  if (f != null) {
    writer.writeInt64(23, f);
  }
  f = message.getObjectIdValue();
  if (f != null) {
    writer.writeMessage(7, f, proto.mongorpc.ObjectID.serializeBinaryToWriter);
  }
};

/**
 * optional double double_value = 1;
 * @return {number}
 */
proto.mongorpc.Value.prototype.getDoubleValue = function () {
  return /** @type {number} */ (
    jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0)
  );
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setDoubleValue = function (value) {
  return jspb.Message.setOneofField(
    this,
    1,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearDoubleValue = function () {
  return jspb.Message.setOneofField(
    this,
    1,
    proto.mongorpc.Value.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasDoubleValue = function () {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * optional string string_value = 2;
 * @return {string}
 */
proto.mongorpc.Value.prototype.getStringValue = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setStringValue = function (value) {
  return jspb.Message.setOneofField(
    this,
    2,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearStringValue = function () {
  return jspb.Message.setOneofField(
    this,
    2,
    proto.mongorpc.Value.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasStringValue = function () {
  return jspb.Message.getField(this, 2) != null;
};

/**
 * optional MapValue map_value = 3;
 * @return {?proto.mongorpc.MapValue}
 */
proto.mongorpc.Value.prototype.getMapValue = function () {
  return /** @type{?proto.mongorpc.MapValue} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.MapValue, 3)
  );
};

/**
 * @param {?proto.mongorpc.MapValue|undefined} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setMapValue = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    3,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearMapValue = function () {
  return this.setMapValue(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasMapValue = function () {
  return jspb.Message.getField(this, 3) != null;
};

/**
 * optional ArrayValue array_value = 4;
 * @return {?proto.mongorpc.ArrayValue}
 */
proto.mongorpc.Value.prototype.getArrayValue = function () {
  return /** @type{?proto.mongorpc.ArrayValue} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.ArrayValue, 4)
  );
};

/**
 * @param {?proto.mongorpc.ArrayValue|undefined} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setArrayValue = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    4,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearArrayValue = function () {
  return this.setArrayValue(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasArrayValue = function () {
  return jspb.Message.getField(this, 4) != null;
};

/**
 * optional bytes bytes_value = 5;
 * @return {string}
 */
proto.mongorpc.Value.prototype.getBytesValue = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};

/**
 * optional bytes bytes_value = 5;
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {string}
 */
proto.mongorpc.Value.prototype.getBytesValue_asB64 = function () {
  return /** @type {string} */ (jspb.Message.bytesAsB64(this.getBytesValue()));
};

/**
 * optional bytes bytes_value = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {!Uint8Array}
 */
proto.mongorpc.Value.prototype.getBytesValue_asU8 = function () {
  return /** @type {!Uint8Array} */ (
    jspb.Message.bytesAsU8(this.getBytesValue())
  );
};

/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setBytesValue = function (value) {
  return jspb.Message.setOneofField(
    this,
    5,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearBytesValue = function () {
  return jspb.Message.setOneofField(
    this,
    5,
    proto.mongorpc.Value.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasBytesValue = function () {
  return jspb.Message.getField(this, 5) != null;
};

/**
 * optional bool bool_value = 8;
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.getBoolValue = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 8, false)
  );
};

/**
 * @param {boolean} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setBoolValue = function (value) {
  return jspb.Message.setOneofField(
    this,
    8,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearBoolValue = function () {
  return jspb.Message.setOneofField(
    this,
    8,
    proto.mongorpc.Value.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasBoolValue = function () {
  return jspb.Message.getField(this, 8) != null;
};

/**
 * optional Timestamp date_value = 9;
 * @return {?proto.mongorpc.Timestamp}
 */
proto.mongorpc.Value.prototype.getDateValue = function () {
  return /** @type{?proto.mongorpc.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Timestamp, 9)
  );
};

/**
 * @param {?proto.mongorpc.Timestamp|undefined} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setDateValue = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    9,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearDateValue = function () {
  return this.setDateValue(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasDateValue = function () {
  return jspb.Message.getField(this, 9) != null;
};

/**
 * optional NullValue null_value = 10;
 * @return {!proto.mongorpc.NullValue}
 */
proto.mongorpc.Value.prototype.getNullValue = function () {
  return /** @type {!proto.mongorpc.NullValue} */ (
    jspb.Message.getFieldWithDefault(this, 10, 0)
  );
};

/**
 * @param {!proto.mongorpc.NullValue} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setNullValue = function (value) {
  return jspb.Message.setOneofField(
    this,
    10,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearNullValue = function () {
  return jspb.Message.setOneofField(
    this,
    10,
    proto.mongorpc.Value.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasNullValue = function () {
  return jspb.Message.getField(this, 10) != null;
};

/**
 * optional int64 integer_value = 23;
 * @return {number}
 */
proto.mongorpc.Value.prototype.getIntegerValue = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setIntegerValue = function (value) {
  return jspb.Message.setOneofField(
    this,
    23,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearIntegerValue = function () {
  return jspb.Message.setOneofField(
    this,
    23,
    proto.mongorpc.Value.oneofGroups_[0],
    undefined
  );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasIntegerValue = function () {
  return jspb.Message.getField(this, 23) != null;
};

/**
 * optional ObjectID object_id_value = 7;
 * @return {?proto.mongorpc.ObjectID}
 */
proto.mongorpc.Value.prototype.getObjectIdValue = function () {
  return /** @type{?proto.mongorpc.ObjectID} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.ObjectID, 7)
  );
};

/**
 * @param {?proto.mongorpc.ObjectID|undefined} value
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.setObjectIdValue = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    7,
    proto.mongorpc.Value.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Value} returns this
 */
proto.mongorpc.Value.prototype.clearObjectIdValue = function () {
  return this.setObjectIdValue(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Value.prototype.hasObjectIdValue = function () {
  return jspb.Message.getField(this, 7) != null;
};
