// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide("proto.mongorpc.CollectionStatsResponse");

goog.require("jspb.BinaryReader");
goog.require("jspb.BinaryWriter");
goog.require("jspb.Message");

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.CollectionStatsResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.CollectionStatsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.CollectionStatsResponse.displayName =
    "proto.mongorpc.CollectionStatsResponse";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.CollectionStatsResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.mongorpc.CollectionStatsResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.CollectionStatsResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.CollectionStatsResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        count: jspb.Message.getFieldWithDefault(msg, 1, 0),
        size: jspb.Message.getFieldWithDefault(msg, 2, 0),
        avgObjSize: jspb.Message.getFieldWithDefault(msg, 3, 0),
        storageSize: jspb.Message.getFieldWithDefault(msg, 4, 0),
        totalIndexSize: jspb.Message.getFieldWithDefault(msg, 5, 0),
        indexSize: jspb.Message.getFieldWithDefault(msg, 6, 0),
        numIndexes: jspb.Message.getFieldWithDefault(msg, 7, 0),
        nindexes: jspb.Message.getFieldWithDefault(msg, 8, 0),
        freeStorageSize: jspb.Message.getFieldWithDefault(msg, 9, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.CollectionStatsResponse}
 */
proto.mongorpc.CollectionStatsResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.CollectionStatsResponse();
  return proto.mongorpc.CollectionStatsResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.CollectionStatsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.CollectionStatsResponse}
 */
proto.mongorpc.CollectionStatsResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setCount(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setSize(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setAvgObjSize(value);
        break;
      case 4:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setStorageSize(value);
        break;
      case 5:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setTotalIndexSize(value);
        break;
      case 6:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setIndexSize(value);
        break;
      case 7:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setNumIndexes(value);
        break;
      case 8:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setNindexes(value);
        break;
      case 9:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setFreeStorageSize(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.CollectionStatsResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.CollectionStatsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.CollectionStatsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.CollectionStatsResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt64(1, f);
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt64(2, f);
  }
  f = message.getAvgObjSize();
  if (f !== 0) {
    writer.writeInt64(3, f);
  }
  f = message.getStorageSize();
  if (f !== 0) {
    writer.writeInt64(4, f);
  }
  f = message.getTotalIndexSize();
  if (f !== 0) {
    writer.writeInt64(5, f);
  }
  f = message.getIndexSize();
  if (f !== 0) {
    writer.writeInt64(6, f);
  }
  f = message.getNumIndexes();
  if (f !== 0) {
    writer.writeInt32(7, f);
  }
  f = message.getNindexes();
  if (f !== 0) {
    writer.writeInt32(8, f);
  }
  f = message.getFreeStorageSize();
  if (f !== 0) {
    writer.writeInt64(9, f);
  }
};

/**
 * optional int64 count = 1;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getCount = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setCount = function (value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};

/**
 * optional int64 size = 2;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getSize = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setSize = function (value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional int64 avg_obj_size = 3;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getAvgObjSize = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setAvgObjSize = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 3, value);
};

/**
 * optional int64 storage_size = 4;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getStorageSize = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setStorageSize = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 4, value);
};

/**
 * optional int64 total_index_size = 5;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getTotalIndexSize =
  function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
  };

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setTotalIndexSize = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 5, value);
};

/**
 * optional int64 index_size = 6;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getIndexSize = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setIndexSize = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 6, value);
};

/**
 * optional int32 num_indexes = 7;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getNumIndexes = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setNumIndexes = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 7, value);
};

/**
 * optional int32 nindexes = 8;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getNindexes = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setNindexes = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 8, value);
};

/**
 * optional int64 free_storage_size = 9;
 * @return {number}
 */
proto.mongorpc.CollectionStatsResponse.prototype.getFreeStorageSize =
  function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
  };

/**
 * @param {number} value
 * @return {!proto.mongorpc.CollectionStatsResponse} returns this
 */
proto.mongorpc.CollectionStatsResponse.prototype.setFreeStorageSize = function (
  value
) {
  return jspb.Message.setProto3IntField(this, 9, value);
};
