// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide("proto.mongorpc.CreateIndexRequest");

goog.require("jspb.BinaryReader");
goog.require("jspb.BinaryWriter");
goog.require("jspb.Message");
goog.require("proto.mongorpc.Index");

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.CreateIndexRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.CreateIndexRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.CreateIndexRequest.displayName =
    "proto.mongorpc.CreateIndexRequest";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.CreateIndexRequest.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.mongorpc.CreateIndexRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.CreateIndexRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.CreateIndexRequest.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        database: jspb.Message.getFieldWithDefault(msg, 1, ""),
        collection: jspb.Message.getFieldWithDefault(msg, 2, ""),
        index:
          (f = msg.getIndex()) &&
          proto.mongorpc.Index.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.CreateIndexRequest}
 */
proto.mongorpc.CreateIndexRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.CreateIndexRequest();
  return proto.mongorpc.CreateIndexRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.CreateIndexRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.CreateIndexRequest}
 */
proto.mongorpc.CreateIndexRequest.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setDatabase(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setCollection(value);
        break;
      case 3:
        var value = new proto.mongorpc.Index();
        reader.readMessage(
          value,
          proto.mongorpc.Index.deserializeBinaryFromReader
        );
        msg.setIndex(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.CreateIndexRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.CreateIndexRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.CreateIndexRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.CreateIndexRequest.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getDatabase();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getCollection();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getIndex();
  if (f != null) {
    writer.writeMessage(3, f, proto.mongorpc.Index.serializeBinaryToWriter);
  }
};

/**
 * optional string database = 1;
 * @return {string}
 */
proto.mongorpc.CreateIndexRequest.prototype.getDatabase = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.mongorpc.CreateIndexRequest} returns this
 */
proto.mongorpc.CreateIndexRequest.prototype.setDatabase = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string collection = 2;
 * @return {string}
 */
proto.mongorpc.CreateIndexRequest.prototype.getCollection = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};

/**
 * @param {string} value
 * @return {!proto.mongorpc.CreateIndexRequest} returns this
 */
proto.mongorpc.CreateIndexRequest.prototype.setCollection = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional Index index = 3;
 * @return {?proto.mongorpc.Index}
 */
proto.mongorpc.CreateIndexRequest.prototype.getIndex = function () {
  return /** @type{?proto.mongorpc.Index} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Index, 3)
  );
};

/**
 * @param {?proto.mongorpc.Index|undefined} value
 * @return {!proto.mongorpc.CreateIndexRequest} returns this
 */
proto.mongorpc.CreateIndexRequest.prototype.setIndex = function (value) {
  return jspb.Message.setWrapperField(this, 3, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.CreateIndexRequest} returns this
 */
proto.mongorpc.CreateIndexRequest.prototype.clearIndex = function () {
  return this.setIndex(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.CreateIndexRequest.prototype.hasIndex = function () {
  return jspb.Message.getField(this, 3) != null;
};
