// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide("proto.mongorpc.Filter");
goog.provide("proto.mongorpc.Filter.OperatorCase");

goog.require("jspb.BinaryReader");
goog.require("jspb.BinaryWriter");
goog.require("jspb.Message");
goog.require("proto.mongorpc.Equal");
goog.require("proto.mongorpc.Exists");
goog.require("proto.mongorpc.Greater");
goog.require("proto.mongorpc.GreaterEqual");
goog.require("proto.mongorpc.In");
goog.require("proto.mongorpc.Less");
goog.require("proto.mongorpc.LessEqual");
goog.require("proto.mongorpc.NotEqual");
goog.require("proto.mongorpc.NotExists");
goog.require("proto.mongorpc.NotIn");

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.Filter = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    null,
    proto.mongorpc.Filter.oneofGroups_
  );
};
goog.inherits(proto.mongorpc.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.Filter.displayName = "proto.mongorpc.Filter";
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.mongorpc.Filter.oneofGroups_ = [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]];

/**
 * @enum {number}
 */
proto.mongorpc.Filter.OperatorCase = {
  OPERATOR_NOT_SET: 0,
  EQUAL: 1,
  NOT_EQUAL: 2,
  LESS: 3,
  LESS_EQUAL: 4,
  GREATER: 5,
  GREATER_EQUAL: 6,
  IN: 7,
  NOT_IN: 8,
  EXISTS: 9,
  NOT_EXISTS: 10,
};

/**
 * @return {proto.mongorpc.Filter.OperatorCase}
 */
proto.mongorpc.Filter.prototype.getOperatorCase = function () {
  return /** @type {proto.mongorpc.Filter.OperatorCase} */ (
    jspb.Message.computeOneofCase(this, proto.mongorpc.Filter.oneofGroups_[0])
  );
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.Filter.prototype.toObject = function (opt_includeInstance) {
    return proto.mongorpc.Filter.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.Filter} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.Filter.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        equal:
          (f = msg.getEqual()) &&
          proto.mongorpc.Equal.toObject(includeInstance, f),
        notEqual:
          (f = msg.getNotEqual()) &&
          proto.mongorpc.NotEqual.toObject(includeInstance, f),
        less:
          (f = msg.getLess()) &&
          proto.mongorpc.Less.toObject(includeInstance, f),
        lessEqual:
          (f = msg.getLessEqual()) &&
          proto.mongorpc.LessEqual.toObject(includeInstance, f),
        greater:
          (f = msg.getGreater()) &&
          proto.mongorpc.Greater.toObject(includeInstance, f),
        greaterEqual:
          (f = msg.getGreaterEqual()) &&
          proto.mongorpc.GreaterEqual.toObject(includeInstance, f),
        pb_in:
          (f = msg.getIn()) && proto.mongorpc.In.toObject(includeInstance, f),
        notIn:
          (f = msg.getNotIn()) &&
          proto.mongorpc.NotIn.toObject(includeInstance, f),
        exists:
          (f = msg.getExists()) &&
          proto.mongorpc.Exists.toObject(includeInstance, f),
        notExists:
          (f = msg.getNotExists()) &&
          proto.mongorpc.NotExists.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.Filter}
 */
proto.mongorpc.Filter.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.Filter();
  return proto.mongorpc.Filter.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.Filter}
 */
proto.mongorpc.Filter.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.mongorpc.Equal();
        reader.readMessage(
          value,
          proto.mongorpc.Equal.deserializeBinaryFromReader
        );
        msg.setEqual(value);
        break;
      case 2:
        var value = new proto.mongorpc.NotEqual();
        reader.readMessage(
          value,
          proto.mongorpc.NotEqual.deserializeBinaryFromReader
        );
        msg.setNotEqual(value);
        break;
      case 3:
        var value = new proto.mongorpc.Less();
        reader.readMessage(
          value,
          proto.mongorpc.Less.deserializeBinaryFromReader
        );
        msg.setLess(value);
        break;
      case 4:
        var value = new proto.mongorpc.LessEqual();
        reader.readMessage(
          value,
          proto.mongorpc.LessEqual.deserializeBinaryFromReader
        );
        msg.setLessEqual(value);
        break;
      case 5:
        var value = new proto.mongorpc.Greater();
        reader.readMessage(
          value,
          proto.mongorpc.Greater.deserializeBinaryFromReader
        );
        msg.setGreater(value);
        break;
      case 6:
        var value = new proto.mongorpc.GreaterEqual();
        reader.readMessage(
          value,
          proto.mongorpc.GreaterEqual.deserializeBinaryFromReader
        );
        msg.setGreaterEqual(value);
        break;
      case 7:
        var value = new proto.mongorpc.In();
        reader.readMessage(
          value,
          proto.mongorpc.In.deserializeBinaryFromReader
        );
        msg.setIn(value);
        break;
      case 8:
        var value = new proto.mongorpc.NotIn();
        reader.readMessage(
          value,
          proto.mongorpc.NotIn.deserializeBinaryFromReader
        );
        msg.setNotIn(value);
        break;
      case 9:
        var value = new proto.mongorpc.Exists();
        reader.readMessage(
          value,
          proto.mongorpc.Exists.deserializeBinaryFromReader
        );
        msg.setExists(value);
        break;
      case 10:
        var value = new proto.mongorpc.NotExists();
        reader.readMessage(
          value,
          proto.mongorpc.NotExists.deserializeBinaryFromReader
        );
        msg.setNotExists(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.Filter.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Filter.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getEqual();
  if (f != null) {
    writer.writeMessage(1, f, proto.mongorpc.Equal.serializeBinaryToWriter);
  }
  f = message.getNotEqual();
  if (f != null) {
    writer.writeMessage(2, f, proto.mongorpc.NotEqual.serializeBinaryToWriter);
  }
  f = message.getLess();
  if (f != null) {
    writer.writeMessage(3, f, proto.mongorpc.Less.serializeBinaryToWriter);
  }
  f = message.getLessEqual();
  if (f != null) {
    writer.writeMessage(4, f, proto.mongorpc.LessEqual.serializeBinaryToWriter);
  }
  f = message.getGreater();
  if (f != null) {
    writer.writeMessage(5, f, proto.mongorpc.Greater.serializeBinaryToWriter);
  }
  f = message.getGreaterEqual();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.mongorpc.GreaterEqual.serializeBinaryToWriter
    );
  }
  f = message.getIn();
  if (f != null) {
    writer.writeMessage(7, f, proto.mongorpc.In.serializeBinaryToWriter);
  }
  f = message.getNotIn();
  if (f != null) {
    writer.writeMessage(8, f, proto.mongorpc.NotIn.serializeBinaryToWriter);
  }
  f = message.getExists();
  if (f != null) {
    writer.writeMessage(9, f, proto.mongorpc.Exists.serializeBinaryToWriter);
  }
  f = message.getNotExists();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.mongorpc.NotExists.serializeBinaryToWriter
    );
  }
};

/**
 * optional Equal equal = 1;
 * @return {?proto.mongorpc.Equal}
 */
proto.mongorpc.Filter.prototype.getEqual = function () {
  return /** @type{?proto.mongorpc.Equal} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Equal, 1)
  );
};

/**
 * @param {?proto.mongorpc.Equal|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setEqual = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    1,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearEqual = function () {
  return this.setEqual(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasEqual = function () {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * optional NotEqual not_equal = 2;
 * @return {?proto.mongorpc.NotEqual}
 */
proto.mongorpc.Filter.prototype.getNotEqual = function () {
  return /** @type{?proto.mongorpc.NotEqual} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.NotEqual, 2)
  );
};

/**
 * @param {?proto.mongorpc.NotEqual|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setNotEqual = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    2,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearNotEqual = function () {
  return this.setNotEqual(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasNotEqual = function () {
  return jspb.Message.getField(this, 2) != null;
};

/**
 * optional Less less = 3;
 * @return {?proto.mongorpc.Less}
 */
proto.mongorpc.Filter.prototype.getLess = function () {
  return /** @type{?proto.mongorpc.Less} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Less, 3)
  );
};

/**
 * @param {?proto.mongorpc.Less|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setLess = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    3,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearLess = function () {
  return this.setLess(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasLess = function () {
  return jspb.Message.getField(this, 3) != null;
};

/**
 * optional LessEqual less_equal = 4;
 * @return {?proto.mongorpc.LessEqual}
 */
proto.mongorpc.Filter.prototype.getLessEqual = function () {
  return /** @type{?proto.mongorpc.LessEqual} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.LessEqual, 4)
  );
};

/**
 * @param {?proto.mongorpc.LessEqual|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setLessEqual = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    4,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearLessEqual = function () {
  return this.setLessEqual(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasLessEqual = function () {
  return jspb.Message.getField(this, 4) != null;
};

/**
 * optional Greater greater = 5;
 * @return {?proto.mongorpc.Greater}
 */
proto.mongorpc.Filter.prototype.getGreater = function () {
  return /** @type{?proto.mongorpc.Greater} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Greater, 5)
  );
};

/**
 * @param {?proto.mongorpc.Greater|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setGreater = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    5,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearGreater = function () {
  return this.setGreater(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasGreater = function () {
  return jspb.Message.getField(this, 5) != null;
};

/**
 * optional GreaterEqual greater_equal = 6;
 * @return {?proto.mongorpc.GreaterEqual}
 */
proto.mongorpc.Filter.prototype.getGreaterEqual = function () {
  return /** @type{?proto.mongorpc.GreaterEqual} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.GreaterEqual, 6)
  );
};

/**
 * @param {?proto.mongorpc.GreaterEqual|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setGreaterEqual = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    6,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearGreaterEqual = function () {
  return this.setGreaterEqual(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasGreaterEqual = function () {
  return jspb.Message.getField(this, 6) != null;
};

/**
 * optional In in = 7;
 * @return {?proto.mongorpc.In}
 */
proto.mongorpc.Filter.prototype.getIn = function () {
  return /** @type{?proto.mongorpc.In} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.In, 7)
  );
};

/**
 * @param {?proto.mongorpc.In|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setIn = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    7,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearIn = function () {
  return this.setIn(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasIn = function () {
  return jspb.Message.getField(this, 7) != null;
};

/**
 * optional NotIn not_in = 8;
 * @return {?proto.mongorpc.NotIn}
 */
proto.mongorpc.Filter.prototype.getNotIn = function () {
  return /** @type{?proto.mongorpc.NotIn} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.NotIn, 8)
  );
};

/**
 * @param {?proto.mongorpc.NotIn|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setNotIn = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    8,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearNotIn = function () {
  return this.setNotIn(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasNotIn = function () {
  return jspb.Message.getField(this, 8) != null;
};

/**
 * optional Exists exists = 9;
 * @return {?proto.mongorpc.Exists}
 */
proto.mongorpc.Filter.prototype.getExists = function () {
  return /** @type{?proto.mongorpc.Exists} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.Exists, 9)
  );
};

/**
 * @param {?proto.mongorpc.Exists|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setExists = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    9,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearExists = function () {
  return this.setExists(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasExists = function () {
  return jspb.Message.getField(this, 9) != null;
};

/**
 * optional NotExists not_exists = 10;
 * @return {?proto.mongorpc.NotExists}
 */
proto.mongorpc.Filter.prototype.getNotExists = function () {
  return /** @type{?proto.mongorpc.NotExists} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.NotExists, 10)
  );
};

/**
 * @param {?proto.mongorpc.NotExists|undefined} value
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.setNotExists = function (value) {
  return jspb.Message.setOneofWrapperField(
    this,
    10,
    proto.mongorpc.Filter.oneofGroups_[0],
    value
  );
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.Filter} returns this
 */
proto.mongorpc.Filter.prototype.clearNotExists = function () {
  return this.setNotExists(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.Filter.prototype.hasNotExists = function () {
  return jspb.Message.getField(this, 10) != null;
};
