// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide("proto.mongorpc.Index");

goog.require("jspb.BinaryReader");
goog.require("jspb.BinaryWriter");
goog.require("jspb.Message");
goog.require("proto.mongorpc.IndexKey");

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.Index = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.mongorpc.Index.repeatedFields_,
    null
  );
};
goog.inherits(proto.mongorpc.Index, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.Index.displayName = "proto.mongorpc.Index";
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mongorpc.Index.repeatedFields_ = [2];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.Index.prototype.toObject = function (opt_includeInstance) {
    return proto.mongorpc.Index.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.Index} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.Index.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        name: jspb.Message.getFieldWithDefault(msg, 1, ""),
        keysList: jspb.Message.toObjectList(
          msg.getKeysList(),
          proto.mongorpc.IndexKey.toObject,
          includeInstance
        ),
        unique: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.Index}
 */
proto.mongorpc.Index.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.Index();
  return proto.mongorpc.Index.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.Index} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.Index}
 */
proto.mongorpc.Index.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setName(value);
        break;
      case 2:
        var value = new proto.mongorpc.IndexKey();
        reader.readMessage(
          value,
          proto.mongorpc.IndexKey.deserializeBinaryFromReader
        );
        msg.addKeys(value);
        break;
      case 3:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setUnique(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.Index.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.Index.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.Index} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.Index.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getKeysList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.mongorpc.IndexKey.serializeBinaryToWriter
    );
  }
  f = message.getUnique();
  if (f) {
    writer.writeBool(3, f);
  }
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.mongorpc.Index.prototype.getName = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.mongorpc.Index} returns this
 */
proto.mongorpc.Index.prototype.setName = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * repeated IndexKey keys = 2;
 * @return {!Array<!proto.mongorpc.IndexKey>}
 */
proto.mongorpc.Index.prototype.getKeysList = function () {
  return /** @type{!Array<!proto.mongorpc.IndexKey>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mongorpc.IndexKey, 2)
  );
};

/**
 * @param {!Array<!proto.mongorpc.IndexKey>} value
 * @return {!proto.mongorpc.Index} returns this
 */
proto.mongorpc.Index.prototype.setKeysList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};

/**
 * @param {!proto.mongorpc.IndexKey=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mongorpc.IndexKey}
 */
proto.mongorpc.Index.prototype.addKeys = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    2,
    opt_value,
    proto.mongorpc.IndexKey,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mongorpc.Index} returns this
 */
proto.mongorpc.Index.prototype.clearKeysList = function () {
  return this.setKeysList([]);
};

/**
 * optional bool unique = 3;
 * @return {boolean}
 */
proto.mongorpc.Index.prototype.getUnique = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 3, false)
  );
};

/**
 * @param {boolean} value
 * @return {!proto.mongorpc.Index} returns this
 */
proto.mongorpc.Index.prototype.setUnique = function (value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};
