// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.mongorpc.ListDocumentsRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.mongorpc.Filter');
goog.require('proto.mongorpc.Sort');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ListDocumentsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mongorpc.ListDocumentsRequest.repeatedFields_, null);
};
goog.inherits(proto.mongorpc.ListDocumentsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ListDocumentsRequest.displayName = 'proto.mongorpc.ListDocumentsRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mongorpc.ListDocumentsRequest.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mongorpc.ListDocumentsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.mongorpc.ListDocumentsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mongorpc.ListDocumentsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ListDocumentsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    database: jspb.Message.getFieldWithDefault(msg, 1, ""),
    collection: jspb.Message.getFieldWithDefault(msg, 2, ""),
    limit: jspb.Message.getFieldWithDefault(msg, 3, 0),
    skip: jspb.Message.getFieldWithDefault(msg, 4, 0),
    filterList: jspb.Message.toObjectList(msg.getFilterList(),
    proto.mongorpc.Filter.toObject, includeInstance),
    sortList: jspb.Message.toObjectList(msg.getSortList(),
    proto.mongorpc.Sort.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ListDocumentsRequest}
 */
proto.mongorpc.ListDocumentsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ListDocumentsRequest;
  return proto.mongorpc.ListDocumentsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ListDocumentsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ListDocumentsRequest}
 */
proto.mongorpc.ListDocumentsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatabase(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCollection(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLimit(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkip(value);
      break;
    case 5:
      var value = new proto.mongorpc.Filter;
      reader.readMessage(value,proto.mongorpc.Filter.deserializeBinaryFromReader);
      msg.addFilter(value);
      break;
    case 6:
      var value = new proto.mongorpc.Sort;
      reader.readMessage(value,proto.mongorpc.Sort.deserializeBinaryFromReader);
      msg.addSort(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ListDocumentsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ListDocumentsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ListDocumentsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ListDocumentsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatabase();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCollection();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSkip();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getFilterList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.mongorpc.Filter.serializeBinaryToWriter
    );
  }
  f = message.getSortList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.mongorpc.Sort.serializeBinaryToWriter
    );
  }
};


/**
 * optional string database = 1;
 * @return {string}
 */
proto.mongorpc.ListDocumentsRequest.prototype.getDatabase = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
 */
proto.mongorpc.ListDocumentsRequest.prototype.setDatabase = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string collection = 2;
 * @return {string}
 */
proto.mongorpc.ListDocumentsRequest.prototype.getCollection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
 */
proto.mongorpc.ListDocumentsRequest.prototype.setCollection = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 limit = 3;
 * @return {number}
 */
proto.mongorpc.ListDocumentsRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
 */
proto.mongorpc.ListDocumentsRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 skip = 4;
 * @return {number}
 */
proto.mongorpc.ListDocumentsRequest.prototype.getSkip = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
 */
proto.mongorpc.ListDocumentsRequest.prototype.setSkip = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated Filter filter = 5;
 * @return {!Array<!proto.mongorpc.Filter>}
 */
proto.mongorpc.ListDocumentsRequest.prototype.getFilterList = function() {
  return /** @type{!Array<!proto.mongorpc.Filter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mongorpc.Filter, 5));
};


/**
 * @param {!Array<!proto.mongorpc.Filter>} value
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
*/
proto.mongorpc.ListDocumentsRequest.prototype.setFilterList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.mongorpc.Filter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mongorpc.Filter}
 */
proto.mongorpc.ListDocumentsRequest.prototype.addFilter = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.mongorpc.Filter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
 */
proto.mongorpc.ListDocumentsRequest.prototype.clearFilterList = function() {
  return this.setFilterList([]);
};


/**
 * repeated Sort sort = 6;
 * @return {!Array<!proto.mongorpc.Sort>}
 */
proto.mongorpc.ListDocumentsRequest.prototype.getSortList = function() {
  return /** @type{!Array<!proto.mongorpc.Sort>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mongorpc.Sort, 6));
};


/**
 * @param {!Array<!proto.mongorpc.Sort>} value
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
*/
proto.mongorpc.ListDocumentsRequest.prototype.setSortList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.mongorpc.Sort=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mongorpc.Sort}
 */
proto.mongorpc.ListDocumentsRequest.prototype.addSort = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.mongorpc.Sort, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mongorpc.ListDocumentsRequest} returns this
 */
proto.mongorpc.ListDocumentsRequest.prototype.clearSortList = function() {
  return this.setSortList([]);
};


