// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide("proto.mongorpc.ListDocumentsResponse");

goog.require("jspb.BinaryReader");
goog.require("jspb.BinaryWriter");
goog.require("jspb.Message");
goog.require("proto.mongorpc.ArrayValue");

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.ListDocumentsResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mongorpc.ListDocumentsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.ListDocumentsResponse.displayName =
    "proto.mongorpc.ListDocumentsResponse";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.ListDocumentsResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.mongorpc.ListDocumentsResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.ListDocumentsResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.ListDocumentsResponse.toObject = function (
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        documents:
          (f = msg.getDocuments()) &&
          proto.mongorpc.ArrayValue.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.ListDocumentsResponse}
 */
proto.mongorpc.ListDocumentsResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.ListDocumentsResponse();
  return proto.mongorpc.ListDocumentsResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.ListDocumentsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.ListDocumentsResponse}
 */
proto.mongorpc.ListDocumentsResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.mongorpc.ArrayValue();
        reader.readMessage(
          value,
          proto.mongorpc.ArrayValue.deserializeBinaryFromReader
        );
        msg.setDocuments(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.ListDocumentsResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.ListDocumentsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.ListDocumentsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.ListDocumentsResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined;
  f = message.getDocuments();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.mongorpc.ArrayValue.serializeBinaryToWriter
    );
  }
};

/**
 * optional ArrayValue documents = 1;
 * @return {?proto.mongorpc.ArrayValue}
 */
proto.mongorpc.ListDocumentsResponse.prototype.getDocuments = function () {
  return /** @type{?proto.mongorpc.ArrayValue} */ (
    jspb.Message.getWrapperField(this, proto.mongorpc.ArrayValue, 1)
  );
};

/**
 * @param {?proto.mongorpc.ArrayValue|undefined} value
 * @return {!proto.mongorpc.ListDocumentsResponse} returns this
 */
proto.mongorpc.ListDocumentsResponse.prototype.setDocuments = function (value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.mongorpc.ListDocumentsResponse} returns this
 */
proto.mongorpc.ListDocumentsResponse.prototype.clearDocuments = function () {
  return this.setDocuments(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mongorpc.ListDocumentsResponse.prototype.hasDocuments = function () {
  return jspb.Message.getField(this, 1) != null;
};
