// source: mongorpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide("proto.mongorpc.NotIn");

goog.require("jspb.BinaryReader");
goog.require("jspb.BinaryWriter");
goog.require("jspb.Message");
goog.require("proto.mongorpc.Value");

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mongorpc.NotIn = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.mongorpc.NotIn.repeatedFields_,
    null
  );
};
goog.inherits(proto.mongorpc.NotIn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mongorpc.NotIn.displayName = "proto.mongorpc.NotIn";
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mongorpc.NotIn.repeatedFields_ = [2];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.mongorpc.NotIn.prototype.toObject = function (opt_includeInstance) {
    return proto.mongorpc.NotIn.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.mongorpc.NotIn} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.mongorpc.NotIn.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        field: jspb.Message.getFieldWithDefault(msg, 1, ""),
        valuesList: jspb.Message.toObjectList(
          msg.getValuesList(),
          proto.mongorpc.Value.toObject,
          includeInstance
        ),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mongorpc.NotIn}
 */
proto.mongorpc.NotIn.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mongorpc.NotIn();
  return proto.mongorpc.NotIn.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mongorpc.NotIn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mongorpc.NotIn}
 */
proto.mongorpc.NotIn.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setField(value);
        break;
      case 2:
        var value = new proto.mongorpc.Value();
        reader.readMessage(
          value,
          proto.mongorpc.Value.deserializeBinaryFromReader
        );
        msg.addValues(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mongorpc.NotIn.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.mongorpc.NotIn.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mongorpc.NotIn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mongorpc.NotIn.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getField();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.mongorpc.Value.serializeBinaryToWriter
    );
  }
};

/**
 * optional string field = 1;
 * @return {string}
 */
proto.mongorpc.NotIn.prototype.getField = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.mongorpc.NotIn} returns this
 */
proto.mongorpc.NotIn.prototype.setField = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * repeated Value values = 2;
 * @return {!Array<!proto.mongorpc.Value>}
 */
proto.mongorpc.NotIn.prototype.getValuesList = function () {
  return /** @type{!Array<!proto.mongorpc.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.mongorpc.Value, 2)
  );
};

/**
 * @param {!Array<!proto.mongorpc.Value>} value
 * @return {!proto.mongorpc.NotIn} returns this
 */
proto.mongorpc.NotIn.prototype.setValuesList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};

/**
 * @param {!proto.mongorpc.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.mongorpc.Value}
 */
proto.mongorpc.NotIn.prototype.addValues = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    2,
    opt_value,
    proto.mongorpc.Value,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mongorpc.NotIn} returns this
 */
proto.mongorpc.NotIn.prototype.clearValuesList = function () {
  return this.setValuesList([]);
};
